### ISSUE TITLE
Too hard to read error need help

### ISSUE THREAD

**Issue by KeenCake** [DogeLord081/OneReality#6]
this is the error messege i cant fix it please help

Traceback (most recent call last):
  File "D:\KeenCake\HEHE\OneReality\OneRealityJPPublic.py", line 208, in <module>
    response_jp = translator.translate(response, src='en', dest='ja')
  File "C:\Users\theka\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "C:\Users\theka\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\theka\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "C:\Users\theka\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by DogeLord081** [comment]
You need a very specific version of googletrans, try `pip uninstall googletrans` and `pip install googletrans==3.1.0a0`
